language: c

# Make sure build dependencies are installed.
install:
 - sudo apt-get update && sudo apt-get install nunit mono-gmcs cli-common-dev libgl1-mesa-dev libsdl1.2-dev libopenal-dev

before_script:
  - export QINIU_ACCESS_KEY="iN7NgwM31j4-BZacMjPrOQBs34UG1maYCAQmhdCV"
  - export QINIU_SECRET_KEY="6QTOr2Jg1gcZEWDQXKOGZh5PziC2MCV5KsntT70j"
  - export QINIU_TEST_BUCKET=""
  - export QINIU_TEST_DOMAIN="aatest.qiniudn.com" 

script:
 - make
 - make test
