#language: objective-c
#
#before_install:
# # Make sure mono is installed,
# - wget http://download.mono-project.com/archive/3.2.0/macos-10-x86/MonoFramework-MDK-3.2.0.macos10.xamarin.x86.pkg
# - hdid MonoFramework-MDK-3.2.0.macos10.xamarin.x86.pkg
# - sudo installer -pkg "/Volumes/Mono Framework MDK 3.2.0/MonoFramework-MDK-3.2.0.macos10.xamarin.x86.pkg" -target /
#
#install:
# - xbuild MonoTravis/MonoTravis.sln
# Travis-CI Build for OpenRA
# see travis-ci.org for details

# Mono/.NET are not officially supported. The following is a workaround.

language: c

# Make sure build dependencies are installed.
install:
 - sudo apt-get update && sudo apt-get install mono-gmcs cli-common-dev libgl1-mesa-dev libsdl1.2-dev libopenal-dev

before_script:
 - export QINIU_ACCESS_KEY="iN7NgwM31j4-BZacMjPrOQBs34UG1maYCAQmhdCV"
 - export QINIU_SECRET_KEY="6QTOr2Jg1gcZEWDQXKOGZh5PziC2MCV5KsntT70j"
 - export QINIU_TEST_BUCKET="a"
 - export QINIU_TEST_DOMAIN="aatest.qiniudn.com"
# Run the build script which will automatically call RALint and ensure that the IDE project files are still valid.
script:
 - xbuild Qiniu.Test/Qiniu.Test.csproj 

